name: flutter_robinhood_siravit
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  collection: ^1.17.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_storage: ^2.1.1
  infinite_scroll_pagination: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  mockito: ^5.4.2
  restart_app: ^1.2.1
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.3

flutter:
  uses-material-design: true

  assets:
    - ./assets/lotties/

  fonts:
    - family: Promp
      fonts:
        - asset: fonts/Prompt-ExtraLight.ttf
          weight: 200
        - asset: fonts/Prompt-Light.ttf
          weight: 300
        - asset: fonts/Prompt-Regular.ttf
        - asset: fonts/Prompt-Medium.ttf
          weight: 500
        - asset: fonts/Prompt-SemiBold.ttf
          weight: 600
        - asset: fonts/Prompt-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/core/gen
  integrations:
    lottie: true
